### PR TITLE
Allow to use secureVarsFile during init

### PR DESCRIPTION
**Pull request by favoretti**
To be able to authenticate to backend by using some remote state data we need to be able to use secureVarsFile to set env vars during init command as well. This should allow for this.

### CODE REVIEW

**Comment by charleszipp** [comment]
Thanks @favoretti for the submission. I will work on reviewing this. Dont worry about the pipeline validation failure. I think some access tokens have expired and need to be updated is the cause. Will reach back out if there is further action needed.

**Comment by favoretti** [comment]
@charleszipp Thanks a lot. Unfortunately I wasn't able to get this to publish to my private repo to test, being a bit noob in the whole extension things, so this is an unverified thought process.. Sorry about that.

**Comment by favoretti** [comment]
Great feedback, thank you very much. I can make it throw en error if command name is init and tfvars file is used as a safeguard option. One thing I would like to ask you - would you be able to share an example pipeline on how to build this extension? I see you're using GitVersions, etc, so if I didn't have to reinvent this wheel it would help me test this a lot. Without ability to build a test version of it modifying it feels like shooting in the dark :)

**Comment by charleszipp** [comment]
> Great feedback, thank you very much. I can make it throw an error if command name is init and tfvars file is used as a safeguard option. One thing I would like to ask you - would you be able to share an example pipeline on how to build this extension? I see you're using GitVersions, etc, so if I didn't have to reinvent this wheel it would help me test this a lot. Without ability to build a test version of it modifying it feels like shooting in the dark :)

@favoretti apologies in the delayed reply. I missed that your last comment in my email notifications. All my attention currently has been focused on project to help with COVID crisis.

I would not recommend recreating the pipeline to test this. However, what I would recommend is using the Upload instructions [here](https://github.com/charleszipp/azure-pipelines-tasks-terraform/tree/master/TerraformCLI#readme) to upload to your own instance of azure devops. After doing this you should be able to view it the same as if it came from the market place. 

This is essentially what the devops pipeline does. During the release it runs the install, delete, and upload scripts against my azure devops instance then runs the task against sample terraform templates. You could do all this from your local dev machine as well to test it out

image

You can also test it without uploading at all and just using env vars using the sample .env file referenced [here](https://github.com/charleszipp/azure-pipelines-tasks-terraform/tree/master/TerraformCLI#create-environment-file). 

Lastly, when i mentioned testing, i was more concerned about updating the existing unit tests to cover the use of .env files during init. Would appreciate if you could add tests to ensure this functionality is covered and protected from potentially future breaking changes.

**Comment by charleszipp** [comment]
Also if it helps, confirmed in the pipeline, im now seeing the secure file drop down for init 
image

**Comment by favoretti** [comment]
@charleszipp Sorry for the long wait, had some context switching to do. I've added tests, please have a look.

**Comment by charleszipp** [comment]
> @charleszipp Sorry for the long wait, had some context switching to do. I've added tests, please have a look.

No worries. I have had a look at the changes and they look good now. Thanks for adding the tests this really helps ensure things stay stable.

I will try to troubleshoot the pipeline to see whats failing there and let you know if any other changes are needed.

**Comment by charleszipp** [comment]
@favoretti the pipeline was failing due to the last test to verify non-env files specified during init fail. The issue was caused by a few minor issues which I corrected. See last commit.

I will keep an eye on the pipeline today as it executes the integration tests and let you know if there are any other changes required.

**Comment by favoretti** [comment]
@charleszipp Oh, that was a stupid mistake on my end. Thanks a lot for fixing! In the meantime I got my uploads to work, so testing in our own pipelines with modded task. One question though, `task.json` in TerraformCLI has 

```
        "Major": "#{GitVersion.Major}#",
        "Minor": "#{GitVersion.Minor}#",
        "Patch": "#{GitVersion.Patch}#"
```

So npm task `upload` fails until I actually set this to something sensible. Am I missing something, or just local overrides are the way to go?

**Comment by charleszipp** [comment]
> @charleszipp Oh, that was a stupid mistake on my end. Thanks a lot for fixing! In the meantime I got my uploads to work, so testing in our own pipelines with modded task. One question though, `task.json` in TerraformCLI has
> 
> ```
>         "Major": "#{GitVersion.Major}#",
>         "Minor": "#{GitVersion.Minor}#",
>         "Patch": "#{GitVersion.Patch}#"
> ```
> 
> So npm task `upload` fails until I actually set this to something sensible. Am I missing something, or just local overrides are the way to go?

Yes thats the way to go. The build pipeline does a token replacement on these as the first step so the artifacts published already have the version set from the build number. So to emulate this behavior locally best way is to probably just set them manually to something that works for your AzDO instance

**Comment by charleszipp** [comment]
@favoretti let me know once you have had a chance to finish up the testing you would like to do in your azure devops instance. Wanted to wait to merge until you had a chance to verify its going to do what you need.

The automation tests in the pipeline have all passed so ready to merge and cut release when you are.

**Comment by favoretti** [comment]
@charleszipp works as intended here :)

**Pull request merged**
