### PR TITLE
Terraform warnings been output as Pipeline warnings

### PR DESCRIPTION
**Pull request by DenWin**
Once again, I apologize for not adding Unit testing for additional or changed logging.
As for testing it in real live, I haven't figured that part out either - unfortunately.

### CODE REVIEW

**Comment by charleszipp** [comment]
Thanks for the contribution @DenWin. I can help get the tests updated to cover this. Will merge once that's been done.

**Comment by DenWin** [comment]
Be advised, these warnings are highly dependent on the AzureRM-version.
That said, are actual plans generated during the Unit tests?

**Comment by charleszipp** [comment]
Actual plans are not generated. The unit tests use sample stdout to mock the execution of terraform plan. The sample stdout is stored in text files. If we wanted to have the tests exercise other terraform providers then we would need samples of those captured for the unit tests to exercise.

**Review by charleszipp — CHANGES_REQUESTED** [review]
@DenWin can you provide an example scenario where the plan would generate a warning you would want visible in the pipeline warnings? Is there some sample output you can provide for testing? Please be sure the output does not contain any secrets or identifying information for your azure resources.

You can add this in the comments if thats easiest. Once I have that I can update the tests to ensure this scenario is covered.

**Comment by DenWin** [comment]
Here is one example:
Having `resource_group_name` in `azurerm_lb_backend_address_pool` is deprecated after azure version 2.57

```
resource azurerm_lb_backend_address_pool "backend_address_pool" {   
    loadbalancer_id                     = data.azurerm_lb.lb.id
    name                                = var.name
    resource_group_name                 = var.lb.resource_group_name
}

```

image

**Comment by DenWin** [comment]
I suggest to postpone this to a later Milestone, as it seems to be hard to cover in a proper test case

**Comment by charleszipp** [comment]
Thanks for the example. I will try to see how we can cover this with a test case. I have moved to next milestone as suggested. Plan on cutting 0.6.24 release for the other improvements today.

**Comment by charleszipp** [comment]
abandoning this since there have been many updates since, lets open as new pr when we want to revisit this

**Pull request closed without merging**
