### PR TITLE
more decisive warnings

### LINKED ISSUE #22: Improvement - more decisive warnings about added, updated or deleted resources
Due to the reconstruction of the repository I cannot see whether a reason existed as to why always all 3 lines are been displayed rather than only those `>0`.

https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/05b63e3915bacfe4f0ed39781bf6a68bc2ea43d9/tasks/terraform-cli/src/commands/tf-plan.ts#L82-L86

I suggest these 2 Improvements:
1) only output those `>0`:
```
private planSummaryReport(toAdd: string, toUpdate: string, toDestroy: string, planName: string) { 
     if (toAdd >0 )      this.logger.warning(`Plan '${planName}' is going to create ${toAdd} resources.`) 
     if (toUpdate>0 )  this.logger.warning(`Plan '${planName}' is going to update ${toUpdate} resources.`) 
     if (toDestroy>0 ) this.logger.warning(`Plan '${planName}' is going to destroy ${toDestroy} resources.`) 
 } 
```
2) Also it is only checked how many resources change, I would like to also see, whether No changes do exist.
```
private planSummaryReport(toAdd: string, toUpdate: string, toDestroy: string, planName: string, noChanges: boolean) { 
     ...
     if (noChanges) this.logger.warning(`Plan '${planName}' shows the infrastructure is up to date and has no changes.`) 
}
```

### PR DESCRIPTION
**Pull request by DenWin**
more decisive warnings
* warning for depricate terraform version
* warning that the infrastructure does not change
* only warn about added, updated or deleted resources if happening

Resolves #22

### CODE REVIEW

**Comment by charleszipp** [comment]
Thanks for the contribution @DenWin. I can help get the tests updated to cover this. Will merge once thats been done.

**Review by charleszipp — APPROVED** [review]

**Comment by charleszipp** [comment]
Changes look good @DenWin and tests have been added to cover the new warning logic. Once pipeline checks pass will merge this one. Thanks again for the contribution.

**Review by charleszipp — CHANGES_REQUESTED** [review]
@DenWin after testing this in the pipeline, the version warning generates quite a bit of noise. This is because each time the task runs, it first runs version. So each instance of the task generates a warning if the version is out of date. 
One idea may be to only generate this warning when only running terraform version. If version is being run as part of another command (init, apply, etc) then dont produce the warning. This would allow users to opt into this behavior by setting up a step to run just version.
image

**Comment by charleszipp** [comment]
> I would suggest, to remove this particular warning, but to add an additional command "version" which only purpose would be to check the version and to output this warning - but on purpose.

This is already possible via 
```yaml
- task: TerraformCLI@0
  displayName: 'check version'
  inputs:
    command: version
    workingDirectory: $(terraform_templates_dir)
```

So just needed to add a check if the task is being run in the context of `terraform version` or another command. If running just for `terraform version` then will check for the warning and emit to pipeline warnings.

**Comment by charleszipp** [comment]
> didn't knew it passes through straight into here. I'm looking into the issue with the error

I found it. There was a period missing at the end of the updated message which was causing the tests to fail. It should be fixed now.

**Comment by DenWin** [comment]
yeah! ... for my defense, the error message coming from npm is hard to read. ;-)

image

**Review by charleszipp — APPROVED** [review]

**Comment by charleszipp** [comment]
build was successful on re-run. github not picking it up. merging...

**Pull request merged**
