### PR TITLE
chore: update task libraries to mask id token

### PR DESCRIPTION
**Pull request by jaredfholgate**
This PR is to mask the idToken generated in WIF. The library was updated to support this functionality, so this change is just an update to the libraries.

### CODE REVIEW

**Comment by jason-johnson** [comment]
I think we need, instead, to update `azure-pipelines-tasks-artifacts-common` to `2.230.0`

**Comment by jaredfholgate** [comment]
Will update the PR accordingly when I get a minute.

**Comment by jaredfholgate** [comment]
@jason-johnson Ready for review. Thanks

**Review by jason-johnson — APPROVED** [review]

**Comment by jason-johnson** [comment]
Letting the pipeline run to completion to make sure the tests are ok, then I'll merge

**Pull request merged**
