### PR TITLE
Add support for terraform output command

### PR DESCRIPTION
**Pull request by charleszipp**
The following adds support for terraform output to be run to emit output variables to pipeline variables.

Couple key points/considerations

1. The variables are set such that they are available to subsequent tasks
2. Only HCL primitive types are supported; string, number, and boolean
3. Ouput variables with complex types such as tuple and object are skipped
4. Sensitive variables are supported. Their values are redacted from the console ouput
5. Terraform command operation is run silently to prevent writing sensitive values to the console.

### CODE REVIEW

**Comment by favoretti** [comment]
LGTM. Wonderful addition, thank you very much, this is super helpful in creating comprehensive pipelines that mix terraform with something else.

**Comment by richardswinbank** [comment]
Just started using the new output option - removes a bunch of redundancy from my pipelines, thanks very much

**Comment by sl-NZ** [comment]
Hi @richardswinbank I was wondering how you consume terraform output, I have a data output defined in my code, I see it during the apply step but right after the apply step I run this task as per below but I still do not see it as a environment value available for consumption.

```
      - task: TerraformCLI@0
        displayName: 'tf output'
        inputs:
          command: 'output'
```

FYI during the Apply step I see the value on the console so atleast 95% sure that terraform is configured correctly.

**Comment by sl-NZ** [comment]
@richardswinbank ignore, I believe it was just the wrong working directory `$(Pipeline.Workspace)` always gets me!

**Pull request merged**
