### PR TITLE
Fix tf-show with tfplan that contains apiManagement policies

### LINKED ISSUE #156: TerraformCLI - "show" does not work for Azure ApiManagement service
**Describe the bug**
TerraformCLI task with command "show" for a tfPlan file generates an error parsing JSON contents.

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)
```
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
        displayName: Terraform plan
        inputs:
          command: plan
          commandOptions: '-detailed-exitcode -out=$(Pipeline.Workspace)/tfplan -input=false ${{ parameters.tfSecrets }}'
          workingDirectory: ${{ parameters.workingDirectory }}
          environmentServiceName: ${{ parameters.backendServicePrincipal }}
          publishPlanResults: ${{ parameters.artifactTfPlanName }}

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
        displayName: Terraform show
        inputs:
          command: show
          environmentServiceName: ${{ parameters.backendServicePrincipal }}
          inputTargetPlanOrStateFilePath: $(Pipeline.Workspace)/tfplan
```
2. Execute pipeline
3. See error
##[error]SyntaxError: Unexpected end of JSON input

**Expected behavior**
TF show finishes and TERRAFORM_PLAN_HAS_DESTROY_CHANGES is set to "true"

**Agent Configuration**
 - OS:  ubuntu-20.04
 - Hosted
 - Terraform version used: 1.0.5
 - AzureCLI version used: default
 - Azurerm provider version used: 2.73.0

**Additional context**
Azure ApiManagement contains policies, that are xml contents. When "show" command is used, it creates blocks like this:
`"xml_content": "\u003cpolicies\u003e\r\n\t\u003cinbound\u003e\r\n\t\t\u003cquota-by-key calls=\"40\" renewal-period=\"3600\" counter-key=\"@(context.Request.IpAddress)\" ...",``
The regex used in tfShow task does not manage tabs and escaped double quotes, so JSON.parse throws an error.

A PR is linked with a test that reproduces the issue and a change at show task that fixes this problem #155

### PR DESCRIPTION
**Pull request by jesusArnas**
tf-show does not work with a tfplan that contains apiManagement policies.
There is a test that reproduces the issue with a "clean" tfplan that contains apiManagement policies.

Fix #156

### CODE REVIEW

**Comment by charleszipp** [comment]
@jesusArnas the test file is 1500 lines long and contains resources that are probably not necessary for the test. Could this be stripped down to just the api management service case that was the original root cause? I appreciate the effort in redacting the plan file but, given the length there is opportunity for something to be missed.

Earlier this year we had someone contribute a similar test file but, there were some credentials that were missed and we ended up having to recreate the repo. Just want to be sure that doesnt happen again.

**Comment by jesusArnas** [comment]
@charleszipp The tfPlan file has been reduced to 700 lines, removing the unnecessary resources. Perhaps the apiM resource could be reduced too, i would prefer keep it as original tfPlan was. What do you think?
Thanks!

**Comment by charleszipp** [comment]
thanks @jesusArnas, the change looks good for now. The pipeline is currently down due to some new security policy restrictions. I am working with the marketplace team find a solution. I will not be able to merge nor publish this change until a solution is reached. Will share updates as I have them.

**Comment by charleszipp** [comment]
@jesusArnas i had to revert main back to a previous tagged release. Since the ci had stopped, main gotten into a bad state and I couldnt track down exactly what broke. Therefore, this PR and your fork have changes that have been removed from main. Since your changes were fairly small, I thought it would be easier to just open a new branch and PR with those changes (rather than trying to figure out how to sync this back up with main). 

I opened #212 which should have your changes and be in sync with main. I am going to close this since it will be replaced by #212

**Pull request closed without merging**
