### PR TITLE
Fix Terraform Plan view when using VisualStudio.com organization url

### LINKED ISSUE #255: publishPlanResults results in a blank Terraform Plan view
Hi!
I'm trying to get some output to the terraform plan view.. The view just shows:
```No terraform plans have been published for this pipeline run. The terraform cli task must run plan with publishPlanResults: string (where string represents the plan name) to view plans.```

I have set the `publishPlanResults` input on the plan task:

```
    - task: TerraformCLI@0
      displayName: 'terraform plan'
      inputs:
          command: plan
          environmentServiceName: 'Dev'
          workingDirectory: 'team-dev-spaces/platform/infrastructure/test-infra-deploy/terraform'
          runAzLogin: true
          publishPlanResults: 'testinfra'
          commandOptions: '-out=$(Pipeline.Workspace)/testinfra.tfplan -detailed-exitcode'
```

I also set System.Debug=true and inspected the debug output of the plan command. I could not see any obvious errors. I have attached the file to this issue.
[tfoutput.txt](https://github.com/charleszipp/azure-pipelines-tasks-terraform/files/6220686/tfoutput.txt)

I'm also publishing the plan result as an artifact (not sure if that is needed):
```
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact: terraform-plans'
      inputs:
        targetPath: $(Pipeline.Workspace)/testinfra.tfplan
        artifact: 'terraform-plans'
```

Is there something I am missing? Does the value in the publishPlanResults input need to have a particular value, matched to something else? I couldn't find anything about this in the docs.

I'm using the latest version of the extension (0.6.15), and the latest version of Terraform (0.14.9). The pipeline is running on an Ubuntu 18.04 agent, and I'm using Azure Storage as the backend storage.

Is this a bug, or a user error (me)? :-)

### PR DESCRIPTION
**Pull request by OmnipotentOwl**
- Update logic for attachment URL parsing to handle legacy VisualStudio.com URL formatting

Fixes #255

### CODE REVIEW

**Review by charleszipp — APPROVED** [review]
This looks good to me. Once the pipeline finishes should be able to verify the original dev.azure.com route still works.

**Comment by charleszipp** [comment]
@OmnipotentOwl I had to push a fake commit to trigger the pipeline. Triggers from forks was disabled

**Comment by FernandoMiguel** [comment]
how do fix releases work?
is there a test build we can use?

**Comment by charleszipp** [comment]
@FernandoMiguel this is being published as 0.6.21 today. There are alpha, beta and RC versions of the extension but they are private. They need to be explicitly shared with organizations. If you would like, I can add you to the list of orgs to share. I would need to know the ADO url to set this up and to which builds you would like to be added.

Alpha -> feature branch (used for manual dev testing)
Beta -> Build triggered from Pull Request merge (i.e. /refs/merge/275)
RC -> Latest from Main
GA/Public version is generated from tagged releases

**Comment by FernandoMiguel** [comment]
we have testing orgs where it would be fine to run RC versions and provide early feedback 
what's the best way to reach you privately ?

**Comment by charleszipp** [comment]
I contacted you at the email you have listed on your profile

**Pull request merged**
