### PR TITLE
additional functionality for terraform output

### PR DESCRIPTION
**Pull request by DenWin**
- TF_OUT-variables are logged now
- warning if a key is not considered

### CODE REVIEW

**Comment by DenWin** [comment]
THese changes will resolve no1&2 for #36

**Comment by DenWin** [comment]
The `convertToHex` function is so one can compare strings why they don't match.

image

Thought this is more of a debug function but one to actually use in the testing.

**Comment by charleszipp** [comment]
@DenWin rather than verifying log messages are appearing by comparing build log samples, i modified this to use the logs that are available from the TestRunner object. From the task.steps.ts, this is accessible via `this.test.logs`. This is an array of the build output. I used this to compare with expected log messages in the feature file. I was concerned that expecting the entire output to match would make the test very prone to failure when adjusting things that have nothing to do with output (version for example which runs with every command). 

I was however, able to take the formatting helpers you added alongside the log messages in the TestRunner and use that to remove completely the need for the `mock-logger.ts` object. This significantly simplified the testing approach for the warning messages. 

Please take a look and let me know if there are any issues with these adjustments. If not, this should be good to merge.

**Comment by DenWin** [comment]
Was fighting quite a bit with the output. Thx, this looks a lot nicer!

**Comment by DenWin** [comment]
there is no test to check whether it is possible to specify a certain output variable rather than all, e.g. 

```
- task                          : charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  inputs:
    command                     : output
    commandOptions              : some_string
```

Though if you test for this the test fails with the message `AssertionError: Error: No exec answer found for command "terraform output -json some_string". Make sure to mock answer for commands!: expected 2 to equal 0`

this error comes from #39 which is somehow related, though only loosely.

Btw. the specific error message only appeared after changing the code as seen in "the error message why a command did not run successful is added"

**Comment by DenWin** [comment]
Btw. the specific error message only appeared after changing the code as seen in "the error message why a command did not run successful is added"

**Comment by DenWin** [comment]
I would go with this one as it is right now.

**Review by charleszipp — APPROVED** [review]

**Pull request merged**
