### PR TITLE
Use -p=secret for azcli login

### PR DESCRIPTION
**Pull request by rubensprt**
Solves the 'unlucky lottery' Azure CLI login issue when the client secret of service principal happens to start with a '-'. 

Azure cli throws the following error when the secret start with a dash:

`Log in with a service principal using client secret. Use -p=secret if the first character of the password is '-'.`

This change simply updates the password argument in the az login command to use `-p=<secret>` instead of `-p <secret>`

### CODE REVIEW

**Comment by jason-johnson** [comment]
Hi, thanks for this.  Right now it seems to be failing in the build pipeline.  I need to figure out why before I can accept it.

**Comment by Aschwinx** [comment]
Would be great if this problem can be solved, nothing more frustrating then a broken pipeline on crucial moments.

**Comment by jason-johnson** [comment]
Hi @rubensprt, could you merge with the latest master?  That will let the tests run so I can verify if this code broke anything (it shouldn't have but Murphy's law, etc.)

**Comment by rubensprt** [comment]
Ive merged main into the branch!

**Review by jason-johnson — APPROVED** [review]
Looks ok to me.

**Comment by jason-johnson** [comment]
Ok, sadly the tests still didn't run on my side but I've went ahead and merged anyway.  You should see the changes show up under `terraformCli@2` in the next few days.

**Comment by jason-johnson** [comment]
@rubensprt The PR seems to break the terraformCli tests.  Did you run these locally before hand?

**Pull request merged**
