### PR TITLE
Add additional arguments to pass in vars to test proper execution

### PR DESCRIPTION
**Pull request by Izzmo**
This is an issue I saw where it is removing double quotes from the command-line options, which affects being able to properly pass in variables like maps and arrays.

[Documentation](https://www.terraform.io/docs/configuration/variables.html#variables-on-the-command-line)

### CODE REVIEW

**Comment by Izzmo** [comment]
@charleszipp any ideas on this? This PR is to get started the issue from my marketplace comment.

**Comment by charleszipp** [comment]
@Izzmo the issue is with the azure-pipelines-task-lib library that is used to run tools on the build agents. This expects options added in a line to be formatted a very specific way. See the function that controls this (here)[https://github.com/microsoft/azure-pipelines-task-lib/blob/ae939a5f51e1c2caa5aaf3f24c67394fa7d3ec85/node/toolrunner.ts#L82]. 

I have committed the way that it expects the string to be formatted. This is how you would input these vars in the terraform task command options field as well.
```javascript
const commandOptions = `-input=true -lock=false -no-color -auto-approve "-var=\\"test_var=test\\"" -var='test_map="{name=\\"test\\",code=\\"abc\\"}"'`
```
The function expects anything with double quotes to be first surrounded by outer double quotes. These outer ones will be stripped off. Then, the quotes you want to keep within have to be escaped by double backslash.

**Comment by Izzmo** [comment]
@charleszipp yuck! But I guess it is what it is. Knowing this, can we can get some documentation around this?

I feel like this is a pretty common use case when using Terraform and people probably just do what I did and revert to an annoying secrets file which is a pain to update.

**Comment by charleszipp** [comment]
@Izzmo i agree this is less than ideal for sure. I think I would prefer to see if its possible to update the task form so that vars have their own section. This is done in other tasks with environment variables. Then i can update the task to format them appropriately so the user doesnt need to know. They just supply the name value pairs.

If there isnt an issue for this already, i will open one to make it easier for users to supply vars.

**Comment by Izzmo** [comment]
@charleszipp sounds good. So can we go ahead and push through this PR and then start another round of edits to modify the task itself -- or would you rather do it all within this?

**Comment by charleszipp** [comment]
Lets do a separate PR tied to #83. I will merge this PR through tomorrow

**Comment by Izzmo** [comment]
@charleszipp okay, sounds good. Thanks!

**Comment by Izzmo** [comment]
@charleszipp Also, that did not seem to work in the current pipeline I have. Here is the output:

```
2019-08-23T16:43:02.8626548Z [command]C:\agent1\_work\_tool\terraform\0.12.6\x64\terraform.exe apply -auto-approve -lock-timeout=5m -var=\\resource_group_name=RG\\ -var='region={name=\\northcentralus\\,code=\\A1\\}' -var='environment={name=\\pc\\,code=\\PC\\}'
2019-08-23T16:43:03.6317227Z ‌
2019-08-23T16:43:03.6318164Z ‌Error: ‌Value for undeclared variable‌
2019-08-23T16:43:03.6318806Z 
2019-08-23T16:43:03.6319380Z ‌A variable named &quot;\\\\resource_group_name&quot; was assigned on the command line,‌
2019-08-23T16:43:03.6319904Z but the root module does not declare a variable of that name. To use this
2019-08-23T16:43:03.6320386Z value, add a "variable" block to the configuration.
```

**Comment by charleszipp** [comment]
@Izzmo Can you post the exact value you put into the command option field minus any secret values?

**Comment by Izzmo** [comment]
@charleszipp it was this:

`-auto-approve -lock-timeout=5m "-var=\\"resource_group_name=$(resourceGroupName)\\"" -var="'region={name=\\"$(regionName)\\",code=\\"$(regionCode)\\"}'" -var="'environment={name=\\"$(envName)\\",code=\\"$(envCode)\\"}'`"

**Comment by georambo** [comment]
I'm having same issue as Izzmo still

commandOptions: -lock=false -input=false -var="\\"management_group_id\\"=${{ parameters.mgmtgroup }}"

is becoming the following

```
/azp/agent/_work/_tool/terraform/0.13.0/x64/terraform plan -lock=false -input=false -var=\\management_group_id\\=iDevOps_MGMT_Testing
```

**Comment by charleszipp** [comment]
since this PR is over a year old and the code has significantly changed since it was opened, closing. feel free to resubmit in new pr with latest.

**Pull request closed without merging**
